export const SET_MASTER_KAB = 'SET_MASTER_KAB';
export const SET_MASTER_BAB = 'SET_MASTER_BAB';
export const SET_MASTER_SATUAN = 'SET_MASTER_SATUAN';
export const SET_MASTER_SUBJECT = 'SET_MASTER_SUBJECT';