export const SET_MASTER_KAB = 'SET_MASTER_KAB';
export const SET_MASTER_BAB = 'SET_MASTER_BAB';
export const SET_MASTER_SATUAN = 'SET_MASTER_SATUAN';
export const SET_MASTER_SUBJECT = 'SET_MASTER_SUBJECT';
export const SET_MASTER_KEC = 'SET_MASTER_KEC';
export const SET_MASTER_DESKEL = 'SET_MASTER_DESKEL';
export const SET_MASTER_VARIABLE = 'SET_MASTER_VARIABLE';
export const SET_MASTER_TABLE = 'SET_MASTER_TABLE';